require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
